infoNavegador = new Object();
infoNavegador.nombre = navigator.appName;
infoNavegador.nombreCodigo = navigator.appCodeName;
infoNavegador.idioma = navigator.language;
infoNavegador.version = navigator.appVersion;
infoNavegador.plataforma = navigator.platform;
infoNavegador.vendedor = navigator.vendor;
infoNavegador.agente = navigator.userAgent;
infoNavegador.javaActivo = navigator.javaEnabled();