document.write("<span><strong>Nombre del código: </strong>" + infoNavegador.nombreCodigo + "</span>");
document.write("<span><strong>Versión: ");
document.write(infoNavegador.version);
document.write("</span>");
document.write("<span><strong>Plataforma: </strong>");
document.write(infoNavegador.plataforma);
document.write("</span>");
document.write("<span><strong>Vendedor: </strong>");
document.write(infoNavegador.vendedor);
document.write("</span>");
document.write("<span><strong>Agente: </strong>");
document.write(infoNavegador.agente);
document.write("</span>");
document.write("<span><strong>Java activo: </strong>");
document.write(infoNavegador.javaActivo);
document.write("</span>");