document.write("<strong>Nombre del código: </strong>" + infoNavegador.nombreCodigo + "<br />");
document.write("<strong>Versión: </strong>");
document.write(infoNavegador.version);
document.write("<br />");
document.write("<strong>Plataforma: </strong>");
document.write(infoNavegador.plataforma);
document.write("<br />");
document.write("<strong>Vendedor: </strong>");
document.write(infoNavegador.vendedor);
document.write("<br />");
document.write("<strong>Agente: </strong>");
document.write(infoNavegador.agente);
document.write("<br />");
document.write("<strong>Java activo: </strong>");
document.write(infoNavegador.javaActivo);
document.write("<br />");