document.write("<section>");
document.write("<h2>Otros datos del navegador</h2>");
document.write("<p><strong>Nombre del código: </strong>" + infoNavegador.nombreCodigo + "</p>");
document.write("<p><strong>Versión: </strong>");
document.write(infoNavegador.version);
document.write("</p>");
document.write("<p><strong>Plataforma: </strong>");
document.write(infoNavegador.plataforma);
document.write("</p>");
document.write("<p><strong>Vendedor: </strong>");
document.write(infoNavegador.vendedor);
document.write("</p>");
document.write("<p><strong>Agente: </strong>");
document.write(infoNavegador.agente);
document.write("</p>");
document.write("<p><strong>Java activo: </strong>");
document.write(infoNavegador.javaActivo);
document.write("</p>");
document.write("</section>");